apiVersion: v1
kind: Service
metadata:
  name: {{ include "hr-chatbot.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "hr-chatbot.name" . }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hr-chatbot.name" . }}
    app.kubernetes.io/component: frontend
